package edu.eci.cosw.spademo.model;
// Generated 10-abr-2016 9:50:56 by Hibernate Tools 4.3.1


import com.fasterxml.jackson.annotation.JsonIgnore;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import org.hibernate.annotations.Fetch;
import org.hibernate.annotations.FetchMode;

/**
 * Roles generated by hbm2java
 */
@Entity
@Table(name="roles")
public class Rol  implements java.io.Serializable {


     private int idRoles;
     private String descripcion;
     private Set<ClientApp> clientsApps = new HashSet<>();

    public Rol() {
    }

	
    public Rol(int idRoles, String descripcion) {
        this.idRoles = idRoles;
        this.descripcion = descripcion;
    }
    public Rol(int idRoles, String descripcion, Set<ClientApp> clientsApps) {
       this.idRoles = idRoles;
       this.descripcion = descripcion;
       this.clientsApps = clientsApps;
    }
   
     @Id 
    //@GeneratedValue(strategy=GenerationType.SEQUENCE)
    @Column(name="id_roles", unique=true, nullable=false)
    public int getIdRoles() {
        return this.idRoles;
    }
    
    public void setIdRoles(int idRoles) {
        this.idRoles = idRoles;
    }

    
    @Column(name="descripcion", nullable=false, length=25)
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }

}


