package edu.eci.cosw.spademo.model;
// Generated 10-abr-2016 9:50:56 by Hibernate Tools 4.3.1


import com.fasterxml.jackson.annotation.JsonIgnore;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import org.hibernate.annotations.Fetch;
import org.hibernate.annotations.FetchMode;

/**
 * Stores generated by hbm2java
 */
@Entity
@Table(name="STORES")
public class Store  implements java.io.Serializable {


     private StoreId id;
     private Supermarket supermarkets;
     private int longitud;
     private int latitud;
     private String nameStore;
     private Set<Zone> zoneses = new HashSet<>();
     private Set<Invoice> invoiceses = new HashSet<>();

    public Store() {
    }

	
    public Store(StoreId id, Supermarket supermarkets, int longitud, int latitud, String nameStore) {
        this.id = id;
        this.supermarkets = supermarkets;
        this.longitud = longitud;
        this.latitud = latitud;
        this.nameStore = nameStore;
    }
    public Store(StoreId id, Supermarket supermarkets, int longitud, int latitud, String nameStore, Set<Zone> zoneses, Set<Invoice> invoiceses) {
       this.id = id;
       this.supermarkets = supermarkets;
       this.longitud = longitud;
       this.latitud = latitud;
       this.nameStore = nameStore;
       this.zoneses = zoneses;
       this.invoiceses = invoiceses;
    }
   
     @EmbeddedId
    @AttributeOverrides( {
        @AttributeOverride(name="idStores", column=@Column(name="id_stores", nullable=false) ), 
        @AttributeOverride(name="superMarketId", column=@Column(name="SuperMarket_id", nullable=false) ) } )
    public StoreId getId() {
        return this.id;
    }
    
    public void setId(StoreId id) {
        this.id = id;
    }

    
    @ManyToOne(cascade = CascadeType.ALL)
    @Fetch(FetchMode.JOIN)
    @JsonIgnore
    @JoinColumn(name="SuperMarket_id", nullable=false, insertable=false, updatable=false)
    public Supermarket getSupermarkets() {
        return this.supermarkets;
    }
    
    public void setSupermarkets(Supermarket supermarkets) {
        this.supermarkets = supermarkets;
    }
    
    
    @Column(name="longitud", nullable=false)
    public int getLongitud() {
        return this.longitud;
    }
    
    public void setLongitud(int longitud) {
        this.longitud = longitud;
    }

    
    @Column(name="latitud", nullable=false)
    public int getLatitud() {
        return this.latitud;
    }
    
    public void setLatitud(int latitud) {
        this.latitud = latitud;
    }

    
    @Column(name="name_store", nullable=false, length=25)
    public String getNameStore() {
        return this.nameStore;
    }
    
    public void setNameStore(String nameStore) {
        this.nameStore = nameStore;
    }

    @OneToMany(cascade = CascadeType.ALL)
    @Fetch(FetchMode.JOIN)
    public Set<Zone> getZoneses() {
        return this.zoneses;
    }
    
    public void setZoneses(Set<Zone> zoneses) {
        this.zoneses = zoneses;
    }

    @OneToMany(cascade = CascadeType.ALL)
    @Fetch(FetchMode.JOIN)
    public Set<Invoice> getInvoiceses() {
        return this.invoiceses;
    }
    
    public void setInvoiceses(Set<Invoice> invoiceses) {
        this.invoiceses = invoiceses;
    }




}


