package edu.eci.cosw.spademo.model;
// Generated 10-abr-2016 9:50:56 by Hibernate Tools 4.3.1

import com.fasterxml.jackson.annotation.JsonIgnore;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import org.hibernate.annotations.Fetch;
import org.hibernate.annotations.FetchMode;

/**
 * Supermarkets generated by hbm2java
 */
@Entity
@Table(name = "supermarkets")
public class Supermarket implements java.io.Serializable {

    private int idSupermarkets;
    private String nameSupermarket;
    private Set<ClientApp> clientsApps = new HashSet<>();

    public Supermarket() {
    }

    public Supermarket(int idSupermarkets, String nameSupermarket) {
        this.idSupermarkets = idSupermarkets;
        this.nameSupermarket = nameSupermarket;
    }

    public Supermarket(int idSupermarkets, String nameSupermarket, Set<ClientApp> clientsApps) {
        this.idSupermarkets = idSupermarkets;
        this.nameSupermarket = nameSupermarket;
        this.clientsApps = clientsApps;
    }

    @Id
    //@GeneratedValue(strategy=GenerationType.SEQUENCE)
    @Column(name = "id_supermarkets", unique = true, nullable = false)
    public int getIdSupermarkets() {
        return this.idSupermarkets;
    }

    public void setIdSupermarkets(int idSupermarkets) {
        this.idSupermarkets = idSupermarkets;
    }

    @Column(name = "name_supermarket", nullable = false, length = 25)
    public String getNameSupermarket() {
        return this.nameSupermarket;
    }

    public void setNameSupermarket(String nameSupermarket) {
        this.nameSupermarket = nameSupermarket;
    }

    @ManyToMany(fetch = FetchType.LAZY)
    @Fetch(FetchMode.JOIN)
    @JsonIgnore
    @JoinTable(name = "clients_markets", joinColumns = {
        @JoinColumn(name = "supermarkets_id_supermarkets")}, inverseJoinColumns = {
        @JoinColumn(name = "client_app_id_clients")})
    public Set<ClientApp> getClientsApps() {
        return this.clientsApps;
    }

    public void setClientsApps(Set<ClientApp> clientsApps) {
        this.clientsApps = clientsApps;
    }
}
