package edu.eci.cosw.spademo.model;
// Generated 10-abr-2016 9:50:56 by Hibernate Tools 4.3.1

import com.fasterxml.jackson.annotation.JsonIgnore;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.JoinColumns;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import org.hibernate.annotations.Fetch;
import org.hibernate.annotations.FetchMode;

/**
 * Zones generated by hbm2java
 */
@Entity
@Table(name = "ZONES")
public class Zone implements java.io.Serializable {

    private ZoneId id;
    private Store stores;
    private String nameZone;
    private Set<Product> productses = new HashSet<>();

    public Zone() {
    }

    public Zone(ZoneId id, Store stores, String nameZone) {
        this.id = id;
        this.stores = stores;
        this.nameZone = nameZone;
    }

    public Zone(ZoneId id, Store stores, String nameZone, Set<Product> productses) {
        this.id = id;
        this.stores = stores;
        this.nameZone = nameZone;
        this.productses = productses;
    }

    @EmbeddedId
    @AttributeOverrides({
        @AttributeOverride(name = "idZones", column = @Column(name = "id_zones", nullable = false)),
        @AttributeOverride(name = "storesIdStores", column = @Column(name = "STORES_id_stores", nullable = false)),
        @AttributeOverride(name = "storesSuperMarketId", column = @Column(name = "STORES_SuperMarket_id", nullable = false))})
    public ZoneId getId() {
        return this.id;
    }

    public void setId(ZoneId id) {
        this.id = id;
    }



    @Column(name = "name_zone", nullable = false, length = 25)
    public String getNameZone() {
        return this.nameZone;
    }

    public void setNameZone(String nameZone) {
        this.nameZone = nameZone;
    }

    @OneToMany(cascade = CascadeType.ALL)
    @Fetch(FetchMode.JOIN)
    public Set<Product> getProductses() {
        return this.productses;
    }

    public void setProductses(Set<Product> productses) {
        this.productses = productses;
    }

}
